permissions:
  pull-requests: write
  contents: read

name: Sticky Comment After Review
on:
  pull_request_review:
    types: [submitted]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "A review has been submitted! Here's an update."
