permissions:
  pull-requests: write
  contents: read

name: Sticky Comment After Review
on:
  pull_request_review:
    types: [submitted]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: |
          ## Pull Request Reviewer Report

          **Author:** [Insert Author Name]  
          **Reviewer:** [Your Name]  
          **Date:** [Insert Date]  
          **Time Taken to Review:** [Insert Time]

          ---
          
          #### Approval Status:
          
          - [ ] Approved
          - [ ] Rejected / Requires Changes
          
          ---
          
          #### Why was it Rejected?
          
          - [ ] Requirement 1 not met
          - [ ] Requirement 2 not met
          - [ ] Requirement 3 not met
          - [ ] Requirement 4 not met
          
          ---
          
          <details>
            <summary>Functional Requirement</summary>
          
          Your hidden content goes here.  
           You can add lists, code, or any markdown content inside.
          
          - Example item 1
          - Example item 2
          
          </details>
          
          ---
          
          <details>
            <summary>Security</summary>
          
          Your hidden content goes here.  
           You can add lists, code, or any markdown content inside.
          
          - Example item 1
          - Example item 2
          
          </details>
          
          ---
          
          <details>
            <summary>Maintainability</summary>
          
          Your hidden content goes here.  
           You can add lists, code, or any markdown content inside.
          
          - Example item 1
          - Example item 2
          
          </details>
          
          ---
          
          <details>
            <summary>Performance</summary>
          
          Your hidden content goes here.  
           You can add lists, code, or any markdown content inside.
          
          - Example item 1
          - Example item 2
          
          </details>
          
          ---
          
          #### Overall Remarks
          
          > [Enter your additional remarks here]

